import { User } from './types';

export const DEFAULT_USER_DATA: User = {
  age: 25,
  gender: 'male',
  height: 180,
  weight: 75,
  activityLevel: 'moderate',
  goal: 'maintain',
  trainingLevel: 'intermediate',
  trainingFrequency: 4,
  foodBudget: undefined,
  budgetLevel: 'medium',
  availableFoods: '',
  dietaryRestrictions: '',
};

export const T_EN = {
    // General
    appTitle: "FitAI Planner",
    // Calculator Form
    personalInfo: "Personal Information",
    age: "Age (years)",
    gender: "Gender",
    male: "Male",
    female: "Female",
    height: "Height (cm)",
    weight: "Weight (kg)",
    lifestyleGoals: "Lifestyle & Goals",
    activityLevel: "Activity Level",
    sedentary: "Sedentary (little or no exercise)",
    light: "Lightly Active (light exercise/sports 1-3 days/week)",
    moderate: "Moderately Active (moderate exercise/sports 3-5 days/week)",
    active: "Very Active (hard exercise/sports 6-7 days a week)",
    goal: "Primary Goal",
    loseWeight: "Lose Weight",
    maintainWeight: "Maintain Weight",
    gainMuscle: "Gain Muscle",
    trainingLevel: "Training Experience",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    trainingFrequency: "Training Days per Week",
    nutritionPrefs: "Nutrition Preferences",
    foodBudget: "Food Budget (per week, optional in EGP)",
    budgetLevel: "Budget Level",
    lowBudget: "Low",
    mediumBudget: "Medium",
    highBudget: "High",
    availableFoods: "Available Foods (optional, comma-separated)",
    dietaryRestrictions: "Dietary Restrictions (optional)",
    calculateButton: "Calculate & Proceed",
    // Results Display
    resultsTitle: "Your Calorie & Macro Goals",
    recalculate: "Recalculate",
    bmr: "Basal Metabolic Rate",
    bmrFormula: "Calories your body burns at rest",
    maintenanceCalories: "Maintenance Calories",
    maintenanceFormula: "Calories to maintain your current weight",
    goalCalories: "Daily Goal Calories",
    goalFormulaLose: "Target for weight loss",
    goalFormulaGain: "Target for muscle gain",
    macros: "Daily Macronutrient Split",
    protein: "Protein",
    carbs: "Carbohydrates",
    fat: "Fat",
    // Plans
    generatePlans: "Generate My Plans",
    regeneratePlans: "Regenerate Plans",
    generatingPlans: "Generating your personalized plans...",
    generatingMealPlan: "Crafting your meal plan...",
    generatingWorkoutPlan: "Designing your workout routine...",
    mealPlanTitle: "Your Personalized Meal Plan",
    workoutPlanTitle: "Your Personalized Workout Plan",
    daySplit: "Day Split",
    targetMuscles: "Target Muscles",
    sets: "Sets",
    reps: "Reps",
    rest: "Rest",
    watchVideo: "Watch Video",
    photoHint: "Photo Hint",
    instructions: "Instructions",
    commonMistakes: "Common Mistakes",
    alternatives: "Alternatives",
    generatePlansPrompt: "Your personalized plans will appear here after generation.",
    // Meal Plan
    ingredients: "Ingredients",
    calories: "Calories",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    snacks: "Snacks",
    dailyTotals: "Daily Totals",
    priceRange: "Est. Price",
    quantity: "Est. Quantity",
};

export const T_AR = {
    // General
    appTitle: "مخطط FitAI",
    // Calculator Form
    personalInfo: "المعلومات الشخصية",
    age: "العمر (سنوات)",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    height: "الطول (سم)",
    weight: "الوزن (كجم)",
    lifestyleGoals: "نمط الحياة والأهداف",
    activityLevel: "مستوى النشاط",
    sedentary: "خامل (قليل أو بدون تمرين)",
    light: "نشاط خفيف (تمارين خفيفة 1-3 أيام/أسبوع)",
    moderate: "نشاط معتدل (تمارين معتدلة 3-5 أيام/أسبوع)",
    active: "نشط جداً (تمارين شاقة 6-7 أيام/أسبوع)",
    goal: "الهدف الأساسي",
    loseWeight: "خسارة الوزن",
    maintainWeight: "الحفاظ على الوزن",
    gainMuscle: "اكتساب العضلات",
    trainingLevel: "مستوى الخبرة في التمرين",
    beginner: "مبتدئ",
    intermediate: "متوسط",
    advanced: "متقدم",
    trainingFrequency: "أيام التمرين في الأسبوع",
    nutritionPrefs: "التفضيلات الغذائية",
    foodBudget: "ميزانية الطعام (أسبوعياً، اختياري بالجنيه المصري)",
    budgetLevel: "مستوى الميزانية",
    lowBudget: "منخفضة",
    mediumBudget: "متوسطة",
    highBudget: "مرتفعة",
    availableFoods: "الأطعمة المتوفرة (اختياري، مفصولة بفواصل)",
    dietaryRestrictions: "القيود الغذائية (اختياري)",
    calculateButton: "احسب وتابع",
    // Results Display
    resultsTitle: "أهدافك من السعرات الحرارية والماكروز",
    recalculate: "إعادة الحساب",
    bmr: "معدل الأيض الأساسي",
    bmrFormula: "السعرات التي يحرقها جسمك في الراحة",
    maintenanceCalories: "سعرات الحفاظ على الوزن",
    maintenanceFormula: "السعرات للحفاظ على وزنك الحالي",
    goalCalories: "السعرات الحرارية المستهدفة يومياً",
    goalFormulaLose: "الهدف لخسارة الوزن",
    goalFormulaGain: "الهدف لاكتساب العضلات",
    macros: "توزيع المغذيات الكبرى اليومي",
    protein: "بروتين",
    carbs: "كربوهيدرات",
    fat: "دهون",
    // Plans
    generatePlans: "أنشئ خططي",
    regeneratePlans: "إعادة إنشاء الخطط",
    generatingPlans: "جاري إنشاء خططك المخصصة...",
    generatingMealPlan: "جاري إعداد خطة وجباتك...",
    generatingWorkoutPlan: "جاري تصميم روتين التمرين الخاص بك...",
    mealPlanTitle: "خطة وجباتك المخصصة",
    workoutPlanTitle: "خطة التمرين المخصصة",
    daySplit: "تقسيم الأيام",
    targetMuscles: "العضلات المستهدفة",
    sets: "مجموعات",
    reps: "تكرارات",
    rest: "راحة",
    watchVideo: "شاهد الفيديو",
    photoHint: "تلميح الصورة",
    instructions: "التعليمات",
    commonMistakes: "الأخطاء الشائعة",
    alternatives: "البدائل",
    generatePlansPrompt: "ستظهر خططك المخصصة هنا بعد إنشائها.",
    // Meal Plan
    ingredients: "المكونات",
    calories: "السعرات الحرارية",
    breakfast: "الإفطار",
    lunch: "الغداء",
    dinner: "العشاء",
    snacks: "وجبات خفيفة",
    dailyTotals: "المجموع اليومي",
    priceRange: "السعر التقديري",
    quantity: "الكمية التقديرية",
};